//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iti.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesbill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public salesbill()
        {
            this.salesbilldetails = new HashSet<salesbilldetail>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string notes { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> totalAdesc { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual customar customar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salesbilldetail> salesbilldetails { get; set; }
        public virtual user user { get; set; }
    }
}
